"""empty message

Revision ID: 149d9a2fbe11
Revises: 1e2fef3179bd
Create Date: 2021-01-25 19:53:27.820972

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '149d9a2fbe11'
down_revision = '1e2fef3179bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tourneystudent', 'reg_status')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tourneystudent', sa.Column('reg_status', sa.TEXT(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
