"""empty message

Revision ID: 16a0c63a8c5a
Revises: edf3136d2ac6
Create Date: 2021-01-09 01:55:24.462322

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16a0c63a8c5a'
down_revision = 'edf3136d2ac6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tourneys', sa.Column('results_date', sa.TIMESTAMP(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tourneys', 'results_date')
    # ### end Alembic commands ###
