"""empty message

Revision ID: 1e2fef3179bd
Revises: 76e4036cecdd
Create Date: 2021-01-25 19:48:38.938067

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e2fef3179bd'
down_revision = '76e4036cecdd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ts_constraint', 'tourneystudent', type_='unique')
    op.create_unique_constraint('ts_constraint', 'tourneystudent', ['tourney_id', 'student_id', 'test'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ts_constraint', 'tourneystudent', type_='unique')
    op.create_unique_constraint('ts_constraint', 'tourneystudent', ['tourney_id', 'student_id'])
    # ### end Alembic commands ###
