"""empty message

Revision ID: 37d8bd4f00fd
Revises: 3adbf3376df1
Create Date: 2021-01-11 01:19:50.626614

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37d8bd4f00fd'
down_revision = '3adbf3376df1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('tdeusername_constraint', 'dataentry', ['tourney_id', 'username'])
    op.drop_constraint('dataentry_username_key', 'dataentry', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('dataentry_username_key', 'dataentry', ['username'])
    op.drop_constraint('tdeusername_constraint', 'dataentry', type_='unique')
    # ### end Alembic commands ###
