"""empty message

Revision ID: 3adbf3376df1
Revises: adc16b2c2c47
Create Date: 2021-01-11 01:13:04.802770

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3adbf3376df1'
down_revision = 'adc16b2c2c47'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dataentry', sa.Column('password', sa.Text(), nullable=False))
    op.add_column('dataentry', sa.Column('username', sa.Text(), nullable=False))
    op.create_unique_constraint(None, 'dataentry', ['username'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'dataentry', type_='unique')
    op.drop_column('dataentry', 'username')
    op.drop_column('dataentry', 'password')
    # ### end Alembic commands ###
