"""empty message

Revision ID: 574bbedab285
Revises: 699ba003d1d6
Create Date: 2020-12-30 16:04:16.322498

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '574bbedab285'
down_revision = '699ba003d1d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tourneystudent',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tourney_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('taking_test', sa.Boolean(), nullable=False),
    sa.Column('test', sa.Text(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('tie', sa.Text(), nullable=False),
    sa.Column('reg_status', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.ForeignKeyConstraint(['tourney_id'], ['tourneys.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tourney_id', 'student_id', name='ts_constraint')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tourneystudent')
    # ### end Alembic commands ###
