"""empty message

Revision ID: 6dfd3c777d16
Revises: 37d8bd4f00fd
Create Date: 2021-01-12 17:11:55.202900

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6dfd3c777d16'
down_revision = '37d8bd4f00fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('tdeusername_constraint', 'dataentry', type_='unique')
    op.create_unique_constraint(None, 'dataentry', ['username'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'dataentry', type_='unique')
    op.create_unique_constraint('tdeusername_constraint', 'dataentry', ['tourney_id', 'username'])
    # ### end Alembic commands ###
