"""empty message

Revision ID: 762ed8a84bf1
Revises: 7a8f5250ad17
Create Date: 2021-01-18 19:45:22.519585

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '762ed8a84bf1'
down_revision = '7a8f5250ad17'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tourneys', sa.Column('info', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tourneys', 'info')
    # ### end Alembic commands ###
