"""empty message

Revision ID: 76e4036cecdd
Revises: f822719004ba
Create Date: 2021-01-24 20:44:12.893259

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76e4036cecdd'
down_revision = 'f822719004ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('name', sa.Text(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'name')
    # ### end Alembic commands ###
