"""empty message

Revision ID: 8ce009ea8142
Revises: fde79d794d29
Create Date: 2021-01-09 18:09:58.528222

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ce009ea8142'
down_revision = 'fde79d794d29'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tourneycollabs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tourney_id', sa.Integer(), nullable=False),
    sa.Column('coach_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['coach_id'], ['coaches.id'], ),
    sa.ForeignKeyConstraint(['tourney_id'], ['tourneys.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tourney_id', 'coach_id', name='tcollab_constraint')
    )
    op.add_column('tourneys', sa.Column('close_date', sa.TIMESTAMP(), nullable=False))
    op.add_column('tourneys', sa.Column('results_date', sa.TIMESTAMP(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tourneys', 'results_date')
    op.drop_column('tourneys', 'close_date')
    op.drop_table('tourneycollabs')
    # ### end Alembic commands ###
