"""empty message

Revision ID: 98068348212a
Revises: 149d9a2fbe11
Create Date: 2021-01-25 19:53:43.194292

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98068348212a'
down_revision = '149d9a2fbe11'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tourneystudent', sa.Column('reg_status', sa.Text(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tourneystudent', 'reg_status')
    # ### end Alembic commands ###
