"""empty message

Revision ID: b6e29fbef792
Revises: 7011258227a4
Create Date: 2021-01-15 18:46:06.463393

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b6e29fbef792'
down_revision = '7011258227a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('schools',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('students', sa.Column('school_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'students', 'schools', ['school_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'students', type_='foreignkey')
    op.drop_column('students', 'school_id')
    op.drop_table('schools')
    # ### end Alembic commands ###
