"""empty message

Revision ID: c72c5fda3510
Revises: 574bbedab285
Create Date: 2021-01-02 02:54:55.552098

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c72c5fda3510'
down_revision = '574bbedab285'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tourneys', 'close_date',
               existing_type=sa.DATE(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tourneys', 'close_date',
               existing_type=sa.DATE(),
               nullable=True)
    # ### end Alembic commands ###
