"""empty message

Revision ID: e6e4fa74710f
Revises: c72c5fda3510
Create Date: 2021-01-02 02:56:00.807103

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e6e4fa74710f'
down_revision = 'c72c5fda3510'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tourneys', 'close_date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tourneys', sa.Column('close_date', sa.DATE(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
