"""empty message

Revision ID: edf3136d2ac6
Revises: e6e4fa74710f
Create Date: 2021-01-02 02:56:10.315065

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'edf3136d2ac6'
down_revision = 'e6e4fa74710f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tourneys', sa.Column('close_date', sa.TIMESTAMP(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tourneys', 'close_date')
    # ### end Alembic commands ###
