"""empty message

Revision ID: f822719004ba
Revises: 9137b5396ef8
Create Date: 2021-01-20 22:00:05.292551

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f822719004ba'
down_revision = '9137b5396ef8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('coaches', sa.Column('stripe_id', sa.Text(), nullable=True))
    op.create_unique_constraint(None, 'coaches', ['stripe_id'])
    op.create_unique_constraint(None, 'orders', ['session_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'orders', type_='unique')
    op.drop_constraint(None, 'coaches', type_='unique')
    op.drop_column('coaches', 'stripe_id')
    # ### end Alembic commands ###
